# Generated by Django 5.0.1 on 2024-01-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homedata_features_customersreview_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
