# Generated by Django 5.0.1 on 2024-01-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_siteinformation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedata',
            name='why_choose_us',
            field=models.TextField(null=True),
        ),
    ]
