# Generated by Django 5.0.1 on 2024-01-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homedata_why_choose_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersreview',
            old_name='title',
            new_name='name',
        ),
    ]
