# Generated by Django 5.0.1 on 2024-01-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_title_customersreview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedata',
            name='contact_title',
        ),
    ]
