# Generated by Django 5.0.1 on 2024-01-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homedata_contact_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedata',
            name='why_choose_us',
        ),
    ]
