# Generated by Django 5.0.1 on 2024-01-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_formdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
