# Generated by Django 5.0.1 on 2024-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_slider_bussines_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='bussines_line_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='bussines_line_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
