# Generated by Django 5.0.1 on 2024-01-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contactus_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
