# Generated by Django 5.0.1 on 2024-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='address_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
