# Generated by Django 5.0.1 on 2024-01-07 08:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='about')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('keywords', models.CharField(max_length=300, null=True)),
                ('seo_description', models.TextField(null=True)),
            ],
        ),
    ]
