# Generated by Django 5.0.1 on 2024-01-08 10:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='ceo_image',
            field=models.ImageField(null=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='ceo_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='ceo_position',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='quote',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
