# Generated by Django 5.0.1 on 2024-01-10 07:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_line', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='keywords_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='keywords_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='seo_description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='seo_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='title_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
